export {default as SmallArrowIcon} from './SmallArrowIcon.vue'
export {default as PlusIcon} from './PlusIcon.vue'
export {default as SearchIcon} from './SearchIcon.vue'
export {default as SpinnerIcon} from './SpinnerIcon.vue'
export {default as NoteIcon} from './NoteIcon.vue'
export {default as ArtistIcon} from './ArtistIcon.vue'
export {default as CrossIcon} from './CrossIcon.vue'
